language: java
jdk:
  - oraclejdk8
install: 
  - pwd
script: 
  - mvn clean verify
  - mvn site:site
  - echo "Hello, World!" > target/site/test.txt
  - mvn site:deploy
cache:
  directories:
  - $HOME/.m2
